import type { Metadata } from "next";
import localFont from "next/font/local";
import { SocketProvider } from "@/contexts/socket";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Deathroll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-dvh" data-theme="dracula">
      <body>
        <SocketProvider>
          <Header />
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
